#---
#Title: Change_Summary
#Author: Thomas Codd - https://github.com/TomCodd
#Contributor: Lucia Segovia de la Revilla  - https://github.com/LuciaSegovia
#Version: V1.0.0
#Changelog:

#Github: https://github.com/TomCodd/NutritionTools
#---

#' @title Change Summary
#' @description
#' @param df
#' @param comment_col Required - default: \code{'comments'} - The name of the
#'   column within \code{df} that contains comments.
#' @param detailed Required - default: \code{FALSE} - \code{TRUE} or
#'   \code{FALSE}. If set to \code{TRUE}, then the Change Summary will examine
#'   the exact comments as they appear in the data frame. If set to
#'   \code{FALSE}, as it is by default, comments which have unique identifiers
#'   (values, imputation IDs etc) have those aspects removed, to reduce the
#'   number of return types.
#' @return A console output detailing how many times one of the comments
#'   generated by functions in NutritionTools appears in the df.
#' @export


Change_Summary <- function(df, comment_col = "comments", detailed = FALSE){

  if(!is.data.frame(df)){ #Checks if the input is a df, stops it if not
    message("Input df is not a data frame. Please input a data frame.")
    return()
  }

  if(!is.character(comment_col)){ #Checks if the comment_col is a character, stops it if not
    message("'comment_col' is not a character. Please input the name of the column where the comments are stored, in quotation marks.")
    return()
  }

  if(!(comment_col %in% colnames(df))){  #Checks if the comment_col is a column in df, stops it if not
    message("'comment_col' is not a column name in df. Please input the name of the column where the comments are stored, in quotation marks.")
    return()
  }

  if(!is.logical(detailed)){ #Checks if detailed is TRUE or FALSE, stops it if not
    message("'detailed' input is not logical. Please use 'TRUE' or 'FALSE'.")
    return()
  }

  comment_column <- df[[comment_col]] #pulls out comment column
  seperated_comments <- unlist(strsplit(comment_column, "; ")) #unlists it

  if(isFALSE(detailed)){ #Goes through the simplification process where relevant
    # Need to simplify the unique markers in comments - for the imputer, its everything after the last 'from'
    seperated_comments[grepl(" value imputed using the ", seperated_comments)] <- sapply(seperated_comments[grepl(" value imputed using the ", seperated_comments)], function(x)
      gsub("(?<=from).*", " [specific FCT(ID)]", as.character(x), perl = TRUE))

    # Next is the CHOAVLDFg values. They all have 'CHOAVLDFg_calculated calculated from 100-[constituents]', and the relevant ones will have ' - Original value of ', [value], ' reset to '
    # Removes the negative number (everything after 'Original value of ' and before ' reset to 0' or ' reset to NA'
    seperated_comments[grepl("CHOAVLDFg_calculated calculated from 100-\\[constituents\\]", seperated_comments) & grepl(" - Original value of ", seperated_comments)] <- sapply(seperated_comments[grepl("CHOAVLDFg_calculated calculated from 100-\\[constituents\\]", seperated_comments) & grepl(" - Original value of ", seperated_comments) & grepl(" reset to ", seperated_comments)], function(x)
      gsub("(?<= - Original value of ).*(?= reset to )", "[Negative Value]", as.character(x), perl = TRUE))
  }

  # Prints output
  message("---------------------------")
  message()
  message("Breakdown of changes made:")
  print(table(seperated_comments))
  message()
  message("---------------------------")
}
